version: "3.8"
services:
  mailtrain:
    image: mailtrain/mailtrain:v2.20210609.0
    ports:
    - 3000:3000
    - 3003:3003
    - 3004:3004
    restart: unless-stopped
    container_name: mailtrain
    volumes:
    - type: volume
      target: /app/server/files
      source: mailtrain-files
    environment:
    - ADMIN_PASSWORD=setAstrongAlphanumericPa55wordH3re
    - PORT_TRUSTED=3000
    - PORT_SANDBOX=3003
    - PORT_PUBLIC=3004
    - URL_BASE_TRUSTED=http://trusted.mailtrain.mydomain.com
    - URL_BASE_SANDBOX=http://sandbox.mailtrain.mydomain.com
    - URL_BASE_PUBLIC=http://public.mailtrain.mydomain.com
    - WWW_PROXY=1
    - WITH_REDIS=0
    - WWW_SECRET=xxxxxxChangeThisxxxxxxxx
    - WITH_ZONE_MTA=0
    - MYSQL_HOST=db
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=MysqlPasswordGoesHere
    depends_on:
    - db
  db:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: db
    volumes:
    - type: volume
      target: /var/lib/mysql
      source: db-data
    environment:
    - MARIADB_RANDOM_ROOT_PASSWORD=1
    - MARIADB_DATABASE=mailtrain
    - MARIADB_USER=mailtrain
    - MARIADB_PASSWORD=MysqlPasswordGoesHere
volumes:
  mailtrain-files:
    driver: local
  db-data:
    driver: local
